import Head from 'next/head';
import katex from 'katex';
var Latex = require('react-latex');

export default function Home({ sheetdata }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="//cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.css"
          rel="stylesheet"
        />
      </Head>

      <main>
        <div className="max-w-xl mb-2 flex items-center justify-center m-auto p-4 bg-gray-200 text-gray-900">
          <div>
            {sheetdata.map((item) => (
              <div>
                {/* Bacaan */}
                <p className="text-center mb-2 indent-8 font-semibold mt-4">
                  {item[2]}
                </p>
                {/* <img src="/image/logolb3r.png" /> */}
                <p className="text-justify mb-2 indent-8">{item[3]}</p>
                <p className="text-justify mb-2 indent-8">{item[4]}</p>
                <p className="text-justify mb-2 indent-8">{item[5]}</p>
                <p className="text-justify mb-2 indent-8">{item[6]}</p>
                <p className="text-justify mb-4 indent-8">{item[7]}</p>
                {/* Tambahan bacaan kolom orange */}
                <p className="text-justify mb-4 indent-8">{item[14]}</p>
                <p className="text-justify mb-4 indent-8">{item[15]}</p>
                <p className="text-justify mb-4 indent-8">{item[16]}</p>
                <p className="text-justify mb-4 indent-8">{item[17]}</p>
                <p className="text-center mb-4 indent-8 font-semibold">
                  {item[18]}
                </p>
                <p className="text-justify mb-4 indent-8">{item[19]}</p>
                <p className="text-justify mb-4 indent-8">{item[20]}</p>
                <p className="text-justify mb-4 indent-8">{item[21]}</p>
                <p className="text-justify mb-4 indent-8">{item[22]}</p>
                <p className="text-justify mb-4 indent-8">{item[23]}</p>
                {/* Pertanyaan */}
                <div className="flex space-x-2 ">
                  <p className="text-justify mb-2 bg-gray-400 p-1">{item[0]}</p>
                  <p className="text-justify mb-2 bg-gray-400 p-1">{item[8]}</p>
                </div>
                {/* Opsi Jawaban */}
                <div className="pr-4 pl-4">
                  <div className="flex space-x-1">
                    <p className="text-justify ">A.</p>
                    <p className="text-justify ">{item[9]}</p>
                  </div>
                  <div className="flex space-x-1">
                    <p className="text-justify ">B.</p>
                    <p className="text-justify ">{item[10]}</p>
                  </div>
                  <div className="flex space-x-1">
                    <p className="text-justify ">C.</p>
                    <p className="text-justify ">{item[11]}</p>
                  </div>
                  <div className="flex space-x-1">
                    <p className="text-justify ">D.</p>
                    <p className="text-justify ">{item[12]}</p>
                  </div>
                  <div className="flex space-x-1">
                    <p className="text-justify ">E.</p>
                    <p className="text-justify mb-2">{item[13]}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </main>
    </div>
  );
}

export async function getServerSideProps() {
  const req = await fetch('http://localhost:3000/api/sheet');
  const res = await req.json();

  return {
    props: {
      sheetdata: res.data,
    },
  };
}
