import Head from 'next/head';
import NavSoal from '../../components/NavSoal';

export default function Home({ sheetdata }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* navigasi soal */}
      <div className="md:flex justify-center fixed bottom-0  overflow-auto left-0 right-0 ">
        <NavSoal sumSoal={sheetdata} />
      </div>
      <main>
        <div className="max-w-xl mb-2 flex items-center justify-center m-auto p-4 bg-gray-200 text-gray-900">
          <div className="mb-12">
            {sheetdata.map((item) => (
              <div>
                {/* Bacaan */}
                <p className="text-center mb-2 indent-8 font-semibold mt-4">
                  {item[2]}
                </p>
                <div className="flex items-center justify-center">
                  <img src={item[27]} className="w-full" />
                </div>
                <p className="text-justify mb-2 indent-8">{item[3]}</p>
                <p className="text-justify mb-2 indent-8">{item[4]}</p>
                <p className="text-justify mb-2 indent-8">{item[5]}</p>
                <p className="text-justify mb-2 indent-8">{item[6]}</p>
                <p className="text-justify mb-4 indent-8">{item[7]}</p>
                {/* Tambahan bacaan kolom orange */}
                <p className="text-justify mb-4 indent-8">{item[14]}</p>
                <p className="text-justify mb-4 indent-8">{item[15]}</p>
                <p className="text-justify mb-4 indent-8">{item[16]}</p>
                <p className="text-justify mb-4 indent-8">{item[17]}</p>
                <p className="text-center mb-4 indent-8 font-semibold">
                  {item[18]}
                </p>
                <p className="text-justify mb-4 indent-8">{item[19]}</p>
                <p className="text-justify mb-4 indent-8">{item[20]}</p>
                <p className="text-justify mb-4 indent-8">{item[21]}</p>
                <p className="text-justify mb-4 indent-8">{item[22]}</p>
                <p className="text-justify mb-4 indent-8">{item[23]}</p>
                {/* Pertanyaan */}
                <div className="flex space-x-2 ">
                  <p className="text-justify mb-2 bg-gray-300 p-1" id={item[0]}>
                    {item[0]}
                  </p>
                  <p className="text-justify mb-2 bg-gray-300 p-1">{item[8]}</p>
                </div>
                {/* Opsi Jawaban */}
                <div className="pr-4 pl-4">
                  <div className="flex space-x-1">
                    <p className="text-justify ">A.</p>
                    <p className="text-justify ">{item[9]}</p>
                  </div>
                  <div className="flex space-x-1">
                    <p className="text-justify ">B.</p>
                    <p className="text-justify ">{item[10]}</p>
                  </div>
                  <div className="flex space-x-1">
                    <p className="text-justify ">C.</p>
                    <p className="text-justify ">{item[11]}</p>
                  </div>
                  <div className="flex space-x-1">
                    <p className="text-justify ">D.</p>
                    <p className="text-justify ">{item[12]}</p>
                  </div>
                  <div className="flex space-x-1">
                    <p className="text-justify ">E.</p>
                    <p className="text-justify mb-2">{item[13]}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </main>
    </div>
  );
}

export async function getServerSideProps() {
  const req = await fetch('https://ruleslb3r.vercel.app/api/sheet');
  const res = await req.json();

  return {
    props: {
      sheetdata: res.data,
    },
  };
}
